### ISSUE TITLE
hwcrypto.js IE10 error

### ISSUE THREAD

**Issue by shkipper** [open-eid/hwcrypto.js#5]
Hi.

Does it support IE9 and IE10 browsers?
 
If I click sign on https://open-eid.github.io/hwcrypto.js/sign.html the page generates error(console output):
 
hwcrypto.js activated
Autodetecting best backend
Assuming IE BHO, testing
Loading plugin for application/x-digidoc into hwcapplicationxdigidoc
Using backend: undefined
Error
{
[functions]: ,
description: "",
message: "",
name: "Error",
number: -2147352567,
stack: "Error
at Anonymous function (https://open-eid.github.io/hwcrypto.js/hwcrypto.js:113:21)
at Promise (https://open-eid.github.io/hwcrypto.js/js/lib/npo.src.js:264:4)
at getCertificate (https://open-eid.github.io/hwcrypto.js/hwcrypto.js:111:13)
at fields.getCertificate (https://open-eid.github.io/hwcrypto.js/hwcrypto.js:251:9)
at sign (https://open-eid.github.io/hwcrypto.js/sign.html:58:5)
at onclick (https://open-eid.github.io/hwcrypto.js/sign.html:128:36)"
}
 
Error: 0 with:
Unknown error: 0 with:
 
(was using IE11 with IE10 Document mode emulation)
 
Thank You.

**Comment by martinpaljak** [comment]
Just received a report that `<meta http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8;" />` in the document makes things bad. This needs a bit research and documentation, turning off the emulation might help ?

**Comment by shkipper** [comment]
With emulation turned off it works fine. But unfortunately we have to support IE9+

**Comment by martinpaljak** [comment]
This can probably be solved with #6

**Comment by martinpaljak** [comment]
This has been fixed in bcf6e4dfb87 and shall be released as 0.0.8 in near minutes
